config/routes.rb
Rails.application.routes.draw do
  resources :lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, :plates, :foods, :reviews, :restaurants, :ingredients

  get "/login", to: "sessions#new"
  post"/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    has_many :ingredients
    belongs_to :plate
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

    belongs_to :food
    validates :name, presence: true
end

app/models/plate.rb
class Plate < ApplicationRecord
    belongs_to :user
    has_many :foods
    has_many :reviews
    # belongs_to :restaurant


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :plates
    has_many :foods, through: :plates
    has_many :users, through: :plates

    validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :plate

    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :plates, dependent: :destroy
    has_many :foods, through: :plates
    has_many :reviews, through: :plates
    has_many :restaurants, through: :plates

    before_validation :downcase_fields
    validates :username, {presence: true, uniqueness: true}
    validates :location, :favorite_food, presence:true

    def downcase_fields
        self.username.downcase!
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user #:logged_in?

    def current_user 
        if session[:user_id] && !session[:user_id].nil?
            @user = User.find_by(:id => session[:user_id])
        else
        end 
    end

    def logged_in?
        !!current_user
    end 

    def authorized
        if logged_in?
            @user = User.find_by(:id => session[:user_id])
        else 
            redirect_to login_path
        end 
    end 

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    before_action :authorized
    before_action :find_food, only: [:show, :edit, :update, :destroy]

    def index
        @foods = Food.all
    end

    def new
        @food = Food.new
    end

    def create
        @food = Food.create(food_params)
        redirect_to food_path(@food)
    end

    def show
    end

    def edit
    end

    def update
        @food.update(food_params)
        redirect_to food_path
    end

    def destroy
        @food.destroy
        redirect_to foods_path
    end

    private

    def find_food 
        @food = Food.find_by(:id => params[:id])
    end

    def food_params
        strong_params = params.require(:food).permit(:name, :plate_id)
    end
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
    before_action :find_plate, only: [:show, :edit, :update, :destroy]
    before_action :authorized
def index
    @plates = Plate.all
end

def new
    @plate = Plate.new
end

def create
    @plate = Plate.create(plate_params)
    if @plate
    redirect_to plate_path(@plate.id)
    end
end

def show
end

def edit
end

def update
    @plate.update(plate_params)
    redirect_to plate_path(@plate)
end

def destroy
    @plate.destroy
    redirect_to user_path(@user)
end

private

def find_plate
    @plate = Plate.find_by(:id => params[:id])
end

def plate_params 
    params.require(:plate).permit(:name, :category, :user_id)
end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authorized
    before_action :find_review, only: [:show, :edit, :update, :destroy]

    def index
        @reviews = Review.all
    end

    def new
        @review = Review.new
    end

    def create
        @review = Review.create(review_params)
        redirect_to review_path(@review)
    end

    def show
    end

    def edit
    end

    def update
        @review.update(review_params)
        redirect_to review_path
    end

    def destroy
        @review.destroy
        redirect_to user_path(@user)
    end

    private

    def find_review
    @review = Review.find_by(:id => params[:id])
    end

    def review_params 
    strong_params = params.require(:review).permit(:title, :content, :user_id, :plate_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to @user
    else
        flash[:error] = "Please try again."
        redirect_to login_path
    end 
end

def destroy
    session[:user_id] = nil
    redirect_to login_path
end

    private

    def session_params
    params.permit(:username, :password)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :authorized, except: [:new, :create]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        # byebug
        @user = User.create(user_params)

        if @user.valid?
            @user.save
        redirect_to user_path(@user)
        else 
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def show
        # byebug
    end

    def edit
    end

    def update
        @user.update(user_params)
        redirect_to user_path(@user)
    end
    
    def destroy
        @user.destroy
        redirect_to users_path
    end

    private 

    def find_user 
        @user = User.find_by(:id => params[:id])
    end 

    def user_params
        strong_params = params.require(:user).permit(:name, :username, :password, :location, :favorite_food)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/foods/edit.html.erb
<%= form_for @food, method: :patch do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> <br>
<%= f.collection_select(:plate_id, Plate.all, :id, :name) %><br>
<%= f.submit %>
<% end %>

app/views/foods/index.html.erb
<h1>Current list of Foods</h1>

<b><%= link_to "Create" , new_food_path %></b>
<ul>
<% @foods.each do |food| %>
<h2>Name:</h2> <b><%= link_to food.name, food_path(food) %></b> <br><br>
<%= link_to "Edit", edit_food_path(food) %>
<%= button_to "Delete", food, :method => :delete, data: {confirm: "Are you sure?"} %>
<% end %>
</ul>

<%= link_to "Back to Plates", plates_path %>

app/views/foods/new.html.erb
<h2>Add food here!</h2>
<b>This should be the actual food on the plate</b><br><br>

<%= form_for @food, method: :post do |f| %>
<b><%= f.label :name %></b>
<%= f.text_field :name %> <br>
<b><%= f.label "Plate Name" %></b>
<%= f.collection_select(:plate_id, Plate.all, :id, :name) %><br>
<%=  %>
<%= f.submit %>
<% end %>

app/views/foods/show.html.erb
<h1> <%= @food.name %> </h1>

<b><%= link_to "Edit", edit_food_path(@food) %></b><br>
<p>

    <h2>Consists of:</h2>
    
    <b><% @food.ingredients.each do |ingredient|%></b>
    <li><b><%= link_to ingredient.name, ingredient_path(ingredient)%></b></li>
    <ol><b><%= ingredient.specifics %></b></ol>
    <% end %>
</p>

<p>
    <h2>Made for:</h2>
    <b><%= link_to @food.plate.name, plate_path %></b><br><br>
</p>


<b><%= link_to "Add Ingredients for your food", new_ingredient_path %></b><br>
<b><%= link_to "Back to Plate", plate_path %> <br></b>
<b><%= link_to "Back to Home", user_path(@user) %></b>

app/views/plates/edit.html.erb
<%= form_for @plate, method: :patch do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> <br>
<%= f.label :category %>
<%= f.text_field :category %> <br>
<b><%= f.label :username %></b>
<%= f.collection_select(:user_id, User.all, :id, :username) %> <br>
<%= f.submit %>
<% end %>

app/views/plates/index.html.erb
<h1> Current list of Plates</h1>
<ul>
<% @plates.each do |plate| %>
<h2>Name:</h2><b> <%= link_to plate.name, plate_path(plate) %></b>
<h3>Category:</h3> <b><%= plate.category %></b> <br><br>
<%= link_to "Edit", edit_plate_path(plate) %>
<%= button_to "Delete", plate, :method => :delete, data: {confirm: "Are you sure?"} %>
<% end %>
</ul>

<b><%= link_to "Back to User" , user_path(@user) %></b>

app/views/plates/new.html.erb
<h1>Prep a new plate here!</h1> 
<b></b>This should be the general name of your plate.</b><br><br>


<%= form_for @plate, method: :post do |f| %>
<b><%= f.label :name %></b>
<b><%= f.text_field :name %> <br></b>
<b><%= f.label :category %></b>
<b><%= f.text_field :category %> <br></b>
<b><%= f.label :username %></b>
<%= f.collection_select(:user_id, User.all, :id, :username) %> <br>
<%= f.submit %>
<% end %>

app/views/plates/show.html.erb
<h1> <%= @plate.name %> </h1>

<b><%= link_to "Edit", edit_plate_path(@plate) %> </b><br>
<b><%= link_to "Add Food to this Plate", new_food_path %> </b><br>
<b><%= link_to "Write a Review", new_review_path %> </b><br>

<p>
    <h2>Food on Plate:</h2>
    <% @plate.foods.map do |food|%>
    <b><%= link_to food.name, food_path %></b><br><br>
    <% end %>

    <h4>Consisting of:</h4> 

    <% @plate.foods.map do |food| %>
    <% food.ingredients.each do |ingredient|%>
    <li><b><%= link_to ingredient.name, ingredient_path(ingredient) %></b></li>
    <% end %>
    <% end %>
</p>

<p>
    <h2>Category:</h2> <b><%= @plate.category %></b>
</p>

<p>
    <h2>Created By:</h2>
    <%= @plate.user.username %>
</p>

<p>
    <h2>Review:</h2>
    <b><% @plate.reviews.each do |review| %></b>
    <b><%= link_to review.title, review_path %></b><br><br>
    <% end %>
</p>


<b><%= link_to "View Plate Page", plates_path %> </b><br>
<b><%= link_to "Back to User Page", user_path %> </b>

app/views/users/edit.html.erb
<%= form_for @user, method: :patch do |f| %>
<%= f.label :username %>
<%= f.text_field :username %> <br>
<%= f.label :location %>
<%= f.text_field :location %> <br>
<%= f.label :favorite_food %>
<%= f.text_field :favorite_food %> <br>
<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1> Current list of Users</h1>

<ul>
    <% @users.each do |user| %>
    <h2>Name:</h2><b><%= user.name %></b>
    <h2>Username:</h2> <b><%= user.username %></b>
    <h2>Location:</h2> <b><%= user.location %></b>
    <h2>Favorite Food:</h2> <b><%= user.favorite_food %></b> <br><br>
    <%= link_to "Edit", edit_user_path(user) %>
    <%= button_to "Delete", user, :method => :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create a new user!</h1>

<%= form_for @user, method: :post do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> <br><br>
<%= f.label :username %>
<%= f.text_field :username %> <br><br>
<%= f.label :password %>
<%= f.text_field :password %> <br><br>
<%= f.label :location %>
<%= f.text_field :location %> <br><br>
<%= f.label :favorite_food %>
<%= f.text_field :favorite_food %> <br><br>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<b><%= link_to "Create a Plate", new_plate_path %></b><br>
<b><%= link_to "Edit Homepage", edit_user_path %> </b>

<p>
    <h2>Username:</h2> <b><%= @user.username %></b>
</p>

<p>
    <h2>Location:</h2> <b><%= @user.location %></b>
</p>

<p>
    <h2>Favorite Food:</h2> <b><%= @user.favorite_food %></b>
</p>

<p>
    <h2>Your Plates:</h2> 
    <% @user.plates.map do |plate|%>
    <li><b><%= link_to plate.name, plate_path(plate) %></b></li>
    <%= button_to "Delete", plate, :method => :delete, data: {confirm: "No longer need this plate?"} %><br>
    <% end %>
</p>

<p>
    <h2>Your Reviews:</h2> 
    
    <% @user.reviews.each do |review|%>
    <li><b><%= link_to review.title, review_path(review) %></b></li>
    <%= button_to "Delete", review, :method => :delete, data: {confirm: "No longer need this review?"} %><br>
    <% end %>
</p>